services:
  - type: web
    name: shop-ease-pro
    env: node
    plan: free
    buildCommand: 'npm install'
    startCommand: 'npm start'
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
    branch: main
    rootDir: .
    
    # Optional: If you want to expose the public directory directly (for static assets)
    staticPublishPath: public
